### ISSUE TITLE
Roadmap to 1.0

### ISSUE THREAD

**Issue by jlchan** [jlchan/StartUpDG.jl#156]
Changes are collected in https://github.com/jlchan/StartUpDG.jl/tree/dev

- [x] Fix triangle node/face ordering https://github.com/jlchan/StartUpDG.jl/pull/153
- [ ] Use https://github.com/YingboMa/SafeTestsets.jl to encapsulate tests 
- [x] Submit PR moving NamedArrayPartition to RecursiveArrayTools.jl
- [ ] [Add tetrahedral SBP operators](https://github.com/jlchan/StartUpDG.jl/issues/13)
- [x] https://github.com/jlchan/StartUpDG.jl/pull/157
- [ ] https://github.com/jlchan/StartUpDG.jl/issues/138

**Comment by jlchan** [comment]
NamedArrayPartition PR in https://github.com/SciML/RecursiveArrayTools.jl/pull/293

**Comment by jlchan** [comment]
PR to switch to RecursiveArrayTools: NamedArrayPartition in https://github.com/jlchan/StartUpDG.jl/pull/159. However, this would also require moving to Julia v1.10

**Comment by jlchan** [comment]
Superceded by https://github.com/jlchan/StartUpDG.jl/pull/160
